# macOS only — Bitwarden session management via Keychain (supports Touch ID)
# Session token is cached in Keychain; falls back to interactive unlock when expired.
if [[ "$OSTYPE" == darwin* ]]; then
  bwu() {
    # Try to restore a cached session (triggers Touch ID / Keychain prompt)
    local session
    session=$(security find-generic-password -a "$USER" -s "bitwarden-session" -w 2>/dev/null)

    if [[ -n "$session" ]]; then
      export BW_SESSION="$session"
      # Validate the session with a real operation, not just bw status (which reports local state)
      if bw list folders --nointeraction 2>/dev/null | grep -q '\['; then
        _bwu_write_secrets
        echo "Bitwarden session restored"
        return 0
      fi
      echo "Session expired, re-unlocking..."
    fi

    # No valid session — unlock interactively and cache the new token
    export BW_SESSION=$(bw unlock --raw)
    if [[ -z "$BW_SESSION" ]]; then
      echo "Unlock failed"
      return 1
    fi

    security delete-generic-password -a "$USER" -s "bitwarden-session" 2>/dev/null || true
    security add-generic-password -a "$USER" -s "bitwarden-session" -w "$BW_SESSION"
    _bwu_write_secrets
    echo "Bitwarden unlocked and session cached"
  }

  # Fetches secrets from Bitwarden and writes them to ~/.secrets (sourced by .zshrc)
  # Add new secrets here following the same pattern.
  _bwu_write_secrets() {
    {
      echo "# Generated by bwu — do not edit manually, re-run bwu to refresh"
      echo "export GITHUB_TOKEN=$(bw get password github-token 2>/dev/null)"
    } > ~/.secrets
    chmod 600 ~/.secrets
  }
fi
